/* =========================
   1) TOUT SUPPRIMER (safe)
   ========================= */

-- Triggers (ORA-04080 = trigger does not exist)
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TR_BIF_RESTAURANTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TR_BIF_TYPES_GASTRONOMIQUES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TR_BIF_VILLES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TR_BIF_COMMENTAIRES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TR_BIF_LIKES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TR_BIF_NOTES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TR_BIF_CRITERES_EVALUATION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF; END;
/

-- Tables (ORA-00942 = table or view does not exist)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RESTAURANTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TYPES_GASTRONOMIQUES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE VILLES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COMMENTAIRES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LIKES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE NOTES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CRITERES_EVALUATION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

-- Sequences (ORA-02289 = sequence does not exist)
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RESTAURANTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TYPES_GASTRONOMIQUES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_VILLES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EVAL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_NOTES'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CRITERES_EVALUATION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/

/* =========================
   2) CREATION TABLES
   ========================= */

CREATE TABLE TYPES_GASTRONOMIQUES (
                                      numero number(10) NOT NULL,
                                      libelle varchar2(100) NOT NULL UNIQUE,
                                      description clob NOT NULL,
                                      PRIMARY KEY (numero)
);

CREATE TABLE VILLES (
                        numero number(10) NOT NULL,
                        code_postal varchar2(100) NOT NULL,
                        nom_ville varchar2(100) NOT NULL,
                        PRIMARY KEY (numero)
);

-- ✅ AJOUT: VERSION (pour @Version)
CREATE TABLE RESTAURANTS (
                             numero number(10) NOT NULL,
                             version number(10) DEFAULT 0 NOT NULL,
                             nom varchar2(100) NOT NULL,
                             adresse varchar2(100) NOT NULL,
                             description clob,
                             site_web varchar2(100),
                             fk_type number(10) NOT NULL,
                             fk_vill number(10) NOT NULL,
                             PRIMARY KEY (numero)
);

CREATE TABLE COMMENTAIRES (
                              numero number(10) NOT NULL,
                              date_eval date NOT NULL,
                              commentaire clob NOT NULL,
                              nom_utilisateur varchar2(100) NOT NULL,
                              fk_rest number(10),
                              PRIMARY KEY (numero)
);

CREATE TABLE LIKES (
                       numero number(10) NOT NULL,
                       appreciation char(1) NOT NULL,
                       date_eval date NOT NULL,
                       adresse_ip varchar2(100) NOT NULL,
                       fk_rest number(10) NOT NULL,
                       PRIMARY KEY (numero)
);

CREATE TABLE CRITERES_EVALUATION (
                                     numero number(10) NOT NULL,
                                     nom varchar2(100) NOT NULL UNIQUE,
                                     description varchar2(512),
                                     PRIMARY KEY (numero)
);

CREATE TABLE NOTES (
                       numero number(10) NOT NULL,
                       note number(3) NOT NULL,
                       fk_comm number(10) NOT NULL,
                       fk_crit number(10) NOT NULL,
                       PRIMARY KEY (numero)
);

ALTER TABLE RESTAURANTS ADD CONSTRAINT FK_REST_TYPE FOREIGN KEY (fk_type) REFERENCES TYPES_GASTRONOMIQUES (numero);
ALTER TABLE RESTAURANTS ADD CONSTRAINT FK_REST_VILL FOREIGN KEY (fk_vill) REFERENCES VILLES (numero);
ALTER TABLE COMMENTAIRES ADD CONSTRAINT FK_COMM_REST FOREIGN KEY (fk_rest) REFERENCES RESTAURANTS (numero);
ALTER TABLE NOTES ADD CONSTRAINT FK_NOTE_COMM FOREIGN KEY (fk_comm) REFERENCES COMMENTAIRES (numero);
ALTER TABLE NOTES ADD CONSTRAINT FK_NOTE_CRIT FOREIGN KEY (fk_crit) REFERENCES CRITERES_EVALUATION (numero);
ALTER TABLE LIKES ADD CONSTRAINT FK_LIKE_REST FOREIGN KEY (fk_rest) REFERENCES RESTAURANTS (numero);

/* =========================
   3) SEQUENCES
   ========================= */

CREATE SEQUENCE SEQ_RESTAURANTS;
CREATE SEQUENCE SEQ_TYPES_GASTRONOMIQUES;
CREATE SEQUENCE SEQ_VILLES;
CREATE SEQUENCE SEQ_EVAL;
CREATE SEQUENCE SEQ_NOTES;
CREATE SEQUENCE SEQ_CRITERES_EVALUATION;

/* =========================
   4) TRIGGERS
   ========================= */

CREATE OR REPLACE TRIGGER TR_BIF_RESTAURANTS
    BEFORE INSERT ON RESTAURANTS
    FOR EACH ROW
BEGIN
    IF :NEW.NUMERO IS NULL THEN
        :NEW.NUMERO := SEQ_RESTAURANTS.NEXTVAL;
    END IF;

    -- (optionnel) si VERSION est null, mettre 0
    IF :NEW.VERSION IS NULL THEN
        :NEW.VERSION := 0;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TR_BIF_TYPES_GASTRONOMIQUES
    BEFORE INSERT ON TYPES_GASTRONOMIQUES
    FOR EACH ROW
BEGIN
    IF :NEW.NUMERO IS NULL THEN
        :NEW.NUMERO := SEQ_TYPES_GASTRONOMIQUES.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TR_BIF_VILLES
    BEFORE INSERT ON VILLES
    FOR EACH ROW
BEGIN
    IF :NEW.NUMERO IS NULL THEN
        :NEW.NUMERO := SEQ_VILLES.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TR_BIF_COMMENTAIRES
    BEFORE INSERT ON COMMENTAIRES
    FOR EACH ROW
BEGIN
    IF :NEW.NUMERO IS NULL THEN
        :NEW.NUMERO := SEQ_EVAL.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TR_BIF_LIKES
    BEFORE INSERT ON LIKES
    FOR EACH ROW
BEGIN
    IF :NEW.NUMERO IS NULL THEN
        :NEW.NUMERO := SEQ_EVAL.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TR_BIF_NOTES
    BEFORE INSERT ON NOTES
    FOR EACH ROW
BEGIN
    IF :NEW.NUMERO IS NULL THEN
        :NEW.NUMERO := SEQ_NOTES.NEXTVAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TR_BIF_CRITERES_EVALUATION
    BEFORE INSERT ON CRITERES_EVALUATION
    FOR EACH ROW
BEGIN
    IF :NEW.NUMERO IS NULL THEN
        :NEW.NUMERO := SEQ_CRITERES_EVALUATION.NEXTVAL;
    END IF;
END;
/
